CREATE PROCEDURE [dbo].[SP_Product_Insert] @CategoryId int,
                                @ProductName nvarchar(200),
                                @ProductDescription nvarchar(500),
                                @MetatagTitle nvarchar(150),
                                @MetatagDescription nvarchar(500),
                                @MetatagKeywords nvarchar(150),
                                @ProductTags nvarchar(150),
                                @ProductCode nvarchar(150),
                                @SKU nvarchar(150),
                                @UPC nvarchar(150),
                                @EAN nvarchar(150),
                                @JAN nvarchar(150),
                                @ISBN nvarchar(150),
                                @MPN nvarchar(150),
                                @Quantity int,
                                @OutOfStockStatus nvarchar(150),
                                @AvailableDate nvarchar(70),
                                @Length numeric(18, 4),
                                @Width numeric(18, 4),
                                @Height numeric(18, 4),
                                @Weight numeric(18, 4),
                                @Status bit,
                                @Brand nvarchar(150),
                                @ImageUrl nvarchar(150)
AS
BEGIN
    SET NOCOUNT ON
    INSERT INTO Products
    (CategoryId, ProductName, ProductDescription, MetatagTitle, MetatagDescription, MetatagKeywords, ProductTags,
     ProductCode, SKU, UPC, EAN, JAN, ISBN, MPN, Quantity, OutOfStockStatus, AvailableDate, Length, Width, Height,
     Weight, Status, Brand, ImageUrl)
    VALUES (@CategoryId,
            @ProductName,
            @ProductDescription,
            @MetatagTitle,
            @MetatagDescription,
            @MetatagKeywords,
            @ProductTags,
            @ProductCode,
            @SKU,
            @UPC,
            @EAN,
            @JAN,
            @ISBN,
            @MPN,
            @Quantity,
            @OutOfStockStatus,
            @AvailableDate,
            @Length,
            @Width,
            @Height,
            @Weight,
            @Status,
            @Brand,
            @ImageUrl)
end
GO
